### ISSUE TITLE
Error internal/crypto/keys ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by lucas-mendes-vidmob** [Lysak/nestjs-fundamentals-course-iluvcoffee#22]
Got an error while running `npm run start:dev`:

[Nest] 27235   - 05/27/2024, 3:41:00 PM   [InstanceLoader] CommonModule dependencies initialized +1ms
node:internal/crypto/keys:596
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received null
    at new NodeError (node:internal/errors:399:5)
    at prepareSecretKey (node:internal/crypto/keys:596:11)
    at new Hmac (node:internal/crypto/hash:136:9)
    at Object.createHmac (node:crypto:165:10)
    at createHMAC (/Users/lucas.mendes/software/nestjs-fundamentals-course-iluvcoffee/node_modules/pg/lib/sasl.js:133:17)
    at Hi (/Users/lucas.mendes/software/nestjs-fundamentals-course-iluvcoffee/node_modules/pg/lib/sasl.js:137:13)
    at Object.continueSession (/Users/lucas.mendes/software/nestjs-fundamentals-course-iluvcoffee/node_modules/pg/lib/sasl.js:32:24)
    at Client._handleAuthSASLContinue (/Users/lucas.mendes/software/nestjs-fundamentals-course-iluvcoffee/node_modules/pg/lib/client.js:257:10)
    at Connection.emit (node:events:513:28)
    at /Users/lucas.mendes/software/nestjs-fundamentals-course-iluvcoffee/node_modules/pg/lib/connection.js:115:12 {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.16.0

**Comment by lucas-mendes-vidmob** [comment]
SOLUTION:

Added password after the : this line in .env file:

`DATABASE_URL=postgres://postgres:pass123@127.0.0.1:5432/postgres`
